### ISSUE TITLE
Help needed - Sharing mimic iii preprocessed file

### ISSUE THREAD

**Issue by khairulislam** [josephenguehard/time_interpret#5]
Hi Joseph, 
Thanks for this great tool. I have using it for my own research and this has been very helpful. I was wondering if it is possible to share the `patient_vital_preprocessed.pkl` file with a drive link. I want to reproduce the results. However, setting up the database and other access is quite time-consuming. It would have been great if I could get the preprocessed file directly.

**Comment by josephenguehard** [comment]
Hi Khairul,

Happy to hear that you like this tool! 

Unfortunately, MIMIC contains real patients' health data, so I am not allowed to share this dataset directly. In order to access it, you need to be an credentialed user and sign the data use agreement (DUA). 

The tutorial to set up the database is quite well explained though: https://mimic.mit.edu/docs/gettingstarted/local/install-mimic-locally-ubuntu, but if you have any questions, I've done it already and would be happy to help!
